<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CS-Script.Core" Version="2.0.0" />
    <PackageVersion Include="CS-Script" Version="4.13.1" />
    <PackageVersion Include="ImeSharp" Version="1.4.1" />
    <PackageVersion Include="NVorbis" Version="0.10.5" />
    <PackageVersion Include="System.Private.Uri" Version="4.3.2" />
    <PackageVersion Include="ManagedBass" Version="4.0.2" />
    <PackageVersion Include="ManagedBass.Midi" Version="4.0.2" />
    <PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Npgsql" Version="10.0.1" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="System.Text.Json" Version="10.0.0" />
    <PackageVersion Include="Eto.Forms" Version="2.10.2" />
    <PackageVersion Include="Eto.Platform.Wpf" Version="2.10.2" />
    <PackageVersion Include="Eto.Platform.Windows" Version="2.10.2" />
    <PackageVersion Include="Eto.Platform.Gtk" Version="2.10.2" />
  </ItemGroup>
</Project>