namespace Core.Net;

public static class Packets
{
    public enum ClientPackets
    {
        // NOTE: The enum ordinal is the wire protocol packet id.
        // Do not reorder existing values.
        CLogin,
        CRegister,
        CAddChar,
        CUseChar,
        CDelChar,
        CLogout,
        CSayMsg,
        CBroadcastMsg,
        CPlayerMsg,
        CAdminMessage,
        CPlayerMove,
        CStopPlayerMove,
        CPlayerDir,
        CUseItem,
        CAttack,
        CPlayerInfoRequest,
        CWarpMeTo,
        CWarpToMe,
        CWarpTo,
        CSetSprite,
        CGetStats,
        CRequestNewMap,
        CNeedMap,
        CMapGetItem,
        CMapDropItem,
        CKickPlayer,
        CBanList,
        CBanDestroy,
        CBanPlayer,
        CRequestEditMap,

        CSetAccess,
        CWhosOnline,
        CSetMotd,
        CSearch,
        CSkills,
        CCast,
        CSwapInvSlots,
        CSwapSkillSlots,

        CCheckPing,
        CUnequip,
        CRequestPlayerData,
        CRequestItem,
        CRequestNpc,
        CRequestResource,
        CSpawnItem,
        CTrainStat,

        CRequestAnimation,
        CRequestSkill,
        CRequestShop,
        CRequestLevelUp,
        CForgetSkill,
        CCloseShop,
        CBuyItem,
        CSellItem,
        CChangeBankSlots,
        CDepositItem,
        CWithdrawItem,
        CCloseBank,
        CAdminWarp,
        CTradeInvite,
        CHandleTradeInvite,
        CAcceptTrade,
        CDeclineTrade,
        CTradeItem,
        CUntradeItem,
        CAdmin,
        CSetHotbarSlot,
        CDeleteHotbarSlot,
        CUseHotbarSlot,
        CEventChatReply,
        CEvent,
        CSwitchesAndVariables,
        CRequestSwitchesAndVariables,

        CRequestProjectile,
        CClearProjectile,
        CEmote,
        CRequestParty,
        CAcceptParty,
        CDeclineParty,
        CLeaveParty,
        CPartyChatMsg,

        // *************************
        // ***   EDITOR PACKETS  ***
        // *************************
        CMapRespawn,
        CMapReport,
        CSaveMap,
        CSkillLearn,

        // ####################
        // ### Dev+ Packets ###
        // ####################
        CRequestEditAnimation,
        CSaveAnimation,
        CRequestEditJob,
        CSaveJob,
        CRequestEditItem,
        CSaveItem,
        CRequestEditNpc,
        CSaveNpc,
        CRequestEditProjectile,
        CSaveProjectile,
        CRequestEditResource,
        CSaveResource,
        CRequestEditShop,
        CSaveShop,
        CRequestEditSkill,
        CSaveSkill,
        CRequestMoral,
        CSaveMoral,
        CRequestEditMoral,

        CSaveScript,
        CRequestEditScript,

        // Mouse-aimed attack (send world pixel target in map space)
        CMouseAttack,
        CCloseEditor,

        CCancelCast
    }

    public enum ServerPackets
    {
        // NOTE: The enum ordinal is the wire protocol packet id.
        // Do not reorder existing values.
        SAes,
        SAlertMsg,
        SLoginOk,
        SPlayerCharacters,
        SJobData,
        SInGame,
        SInventory,
        SInventoryUpdate,
        SPlayerWornEq,
        SPlayerHP,
        SPlayerMP,
        SPlayerSP,
        SPlayerStats,
        SPlayerData,
        SPlayerMove,
        SNpcMove,
        SPlayerDir,
        SNpcDir,
        SPlayerXY,
        SAttack,
        SNpcAttack,
        SCheckForMap,
        SMapData,
        SMapItemData,
        SMapItemsData,
        SMapNpcData,
        SMapNpcUpdate,
        SGlobalMsg,
        SSendAdminMessage,
        SPlayerMsg,
        SSendMapMessage,
        SSpawnItem,
        SItemEditor,
        SUpdateItem,
        SSpawnNpc,
        SNpcDead,
        SNpcEditor,
        SUpdateNpc,
        SEditMap,
        SShopEditor,
        SUpdateShop,
        SSkillEditor,
        SUpdateSkill,
        SSkills,
        SLeftMap,
        SMapResource,
        SResourceEditor,
        SUpdateResource,
        SSendPing,
        SActionMessage,
        SPlayerExp,
        SBlood,
        SAnimationEditor,
        SUpdateAnimation,
        SAnimation,
        SMapNpcVitals,
        SCooldown,
        SClearSkillBuffer,
        SStartSkillBuffer,
        SSayMsg,
        SOpenShop,
        SResetShopAction,
        SStunned,
        SMapWornEq,
        SBank,
        SLeftGame,
        STradeInvite,
        STrade,
        SCloseTrade,
        STradeUpdate,
        STradeStatus,
        SMapReport,
        STarget,
        SAdmin,
        SMapNames,
        SCritical,
        SrClick,
        SHotbar,
        SSpawnEvent,
        SEventMove,
        SEventDir,
        SEventChat,
        SEventStart,
        SEventEnd,
        SPlayBgm,
        SPlaySound,
        SFadeoutBgm,
        SStopSound,
        SSwitchesAndVariables,
        SMapEventData,
        SChatBubble,
        SSpecialEffect,
        SPic,
        SHoldPlayer,
        SProjectileEditor,
        SUpdateProjectile,
        SMapProjectile,
        SJobEditor,
        SUpdateJob,
        SUpdateMoral,
        SEmote,
        SPartyInvite,
        SPartyUpdate,
        SPartyVitals,
        SMoralEditor,
        STime,
        SClock,
        SScriptEditor,
        SPlayerDead,
        SVariables
    }
}