<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net10.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
	    <UseSharedCompilation>false</UseSharedCompilation>
	    <AssemblyTitle>XtremeWorlds.Core</AssemblyTitle>
	    <AssemblyName>XtremeWorlds.Core</AssemblyName>
	    <AssemblyRootSpace>XtremeWorlds.Core</AssemblyRootSpace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CS-Script" />
        <PackageReference Include="CS-Script.Core" />
    </ItemGroup>
</Project>
