name: Release

on:
  push:
    tags:
      - "*"  # triggers on any tag

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Client
        run: dotnet build Source/Client/Client.csproj --configuration Release --no-restore
      - name: Build Server
        run: dotnet build Source/Server/Server.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish Client
        run: dotnet publish Source/Client/Client.csproj -c Release -o ./publish/Client --self-contained true
      - name: Publish Server
        run: dotnet publish Source/Server/Server.csproj -c Release -o ./publish/Server --self-contained true

      # Linux ZIP
      - name: Create ZIP on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          OS=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          cd publish
          zip -r "../xtremeworlds-${OS}-${GITHUB_REF_NAME}.zip" *
          cd ..
      - name: Upload ZIP on Linux
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: xtremeworlds-linux-${{ github.ref_name }}
          path: xtremeworlds-linux-${{ github.ref_name }}.zip
      # Windows ZIP
      - name: Create ZIP on Windows
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: |
          $OS = $env:RUNNER_OS.ToLower()
          $ZIP = "..\xtremeworlds-$OS-$env:GITHUB_REF_NAME.zip"
          Compress-Archive -Path publish\* -DestinationPath $ZIP
      - name: Upload ZIP on Windows
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v4
        with:
          name: xtremeworlds-windows-${{ github.ref_name }}
          path: ../xtremeworlds-windows-${{ github.ref_name }}.zip
